language: java
dist: xenial
jdk: openjdk14
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: SONAR_ORGANIZATION
    token: $SONAR_TOKEN

script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - $HOME/ .m2
    - $home/.sonar/cache
notifications:
  email:
    recipients:
      - ferhmdiogo@gmail.com
    on_success: always # default: change
    on_failure: always # default: always


